Repository cypress-io/cypress-documentation, pull requests merged in 2022-04, with the labels that each got.

#4418 CLOUD-538: Update GitHub Enterprise docs to remove reference to Preview
  content/guides/dashboard/github-integration.md
Labels: content: remove, section: dashboard

#4371 UDX-94-new-sidebar-unification
  assets/cy-logo.png
  assets/cydocs-logo.png
  assets/cypress-logo.png
  assets/cypress-logo.svg
  components/AppHeader.vue
  components/AppHeaderMobileSection.vue
  components/AppSidebar.vue
Labels: unification

#4420 CLOUD-351: Update GitHub Enterprise docs minimal repository permissions screenshot
  assets/img/dashboard/github-integration/ghe/ghe-04.png
Labels: content: rewrite, section: dashboard

#4430 Badge padding issue
  components/global/Badge.vue
  components/global/CodeGroup.vue
  content/guides/references/migration-guide.md
  static/favicon.ico
  static/img/favicon.ico
Labels: unification

#4429 docs: update writing first test ct guide
  content/guides/getting-started/writing-your-first-component-test.md
Labels: unification

#4434 docs: updating faq with ct specific info
  content/faq/questions/using-cypress-faq.md
Labels: unification

#4432 docs: update migration guide for ct changes
  content/guides/references/migration-guide.md
Labels: unification

#4428 docs: update mount api doc for ct changes
  components/global/CodeGroupReactVue2Vue3.vue
  components/global/CodeGroupVue2Vue3.vue
  content/api/commands/mount.md
Labels: unification

#4426 docs: update mount partial for new imports
  content/partials/import-mount-functions.md
Labels: unification

#4424 docs: update config ref guide for ct arch changes
  content/guides/references/configuration.md
Labels: unification

#4422 docs: updates to ct framework config for new ct arch
  content/guides/getting-started/component-framework-configuration.md
Labels: unification

#4421 docs: adding ct beta alert box to needed pages
  components/global/CtBetaAlert.vue
  content/api/commands/mount.md
  content/guides/getting-started/component-framework-configuration.md
  content/guides/getting-started/getting-components-to-work.md
  content/guides/getting-started/rendering-components-correctly.md
  content/guides/getting-started/writing-your-first-component-test.md
Labels: unification

#4449 Update references Experiments page with new option
  content/guides/references/experiments.md
Labels: content: new, section: guides

#4448 Update cy.session command API page
  content/api/commands/session.md
Labels: content: new, section: api

#4452 Update cy.origin API docs with last-minute changes
  content/api/commands/origin.md
Labels: content: rewrite, section: api

#4454 Fix typos in migration code examples
  content/api/commands/origin.md
Labels: content: rewrite, section: api

#4455 feat(plugins): add cypress chrome recorder to plugins page
  content/_data/plugins.json
Labels: section: plugins
